### ISSUE TITLE
Implement loading message/icon while fetching weather data

### ISSUE THREAD

**Issue by andrewkykoo** [andrewkykoo/goals-frontend#4]
At the moment, only loading messages/texts are displayed while loading the weather data. For more dynamic design, we should implement loading icons (e.g., spinners).  I suggest using chakra-ui library.

**Comment by iusamahub** [comment]
please assign me this issue @andrewkykoo

**Comment by andrewkykoo** [comment]
Hi @iusamahub, thanks for helping out! I have just assigned this issue to you. Let me know if you have any questions!
